### ISSUE TITLE
Question: RHEL 8 support

### ISSUE THREAD

**Issue by moritzdietz** [theforeman/puppet-katello#397]
As noted in the README as of now RHEL 8 is not supported.
Is this a hard limit or is this just something where it wasn't properly tested on RHEL 8?

We are in the middle of setting up and are somewhat set on RHEL 8.
Would've been a bummer if we had to spin up a single RHEL 7 node for something small.

**Comment by evgeni** [comment]
Katello didn't support EL8 until 4.0 (which is currently RC phase), so the readme should be updated.

**Comment by moritzdietz** [comment]
Exactly this is what I pointed out to my colleague. We just weren't 100% sure as the limit was *specifically* written out in the README.
But now that that is cleared up I feel good with moving forward using RHEL 8.

Thanks for getting to this so quickly! Much appreciated.

**Comment by evgeni** [comment]
Reopening so we actually fix the readme too
